### ISSUE TITLE
Programador arduino mini pro

### ISSUE THREAD

**Issue by Jaimee007** [asrob-uc3m/ASROB-racing#7]
Necesario encontrar un programador para poder usar el arduino.

**Comment by David-Estevez** [comment]
El otro día usamos el de UC3Music, así que voy a invocar a @JorFru para que nos diga si UC3Music dispone de más de uno, y si sería posible que se nos cediese alguno mediante algún tipo de acuerdo en el que ambas partes ganásemos.

Buscaré también el mío y si lo encuentro me lo llevo el próximo día.

**Comment by JorFru** [comment]
En UC3Music no tenemos más de uno, según mi conocimiento.
Pero el que te presté el día anterior no lo estábamos usando usando ni lo
usaremos en ningún proyecto del futuro cercano.



*El programador lo cedemos a ASROB en calidad de préstamo.*
Por ahora de manera indefinida. Si se da el remoto caso de que en UC3Music
lo necesitamos, se pedirá de vuelta con suficiente tiempo de antelación.

PD: disfrutad de él!

**Comment by physedu** [comment]
yo soy tu hombre, 15 euro/h
