### ISSUE TITLE
Jaime compra cables

### ISSUE THREAD

**Issue by physedu** [asrob-uc3m/ASROB-racing#8]

**Comment by physedu** [comment]
@David-Estevez @Jaimee007

**Comment by David-Estevez** [comment]
Si los compras tú, @Jaimee007 luego abrimos una issue como https://github.com/asrob-uc3m/actas/issues/125 para que se te devuelva el dinero.

Si no los quieres comprar tú, pues habrá que abrir la issue primero y cuando se apruebe comprarlos.

Por rapidez, quizá @wenflehecanario pueda comprarlos a través de Amazon Prime.

¿Qué opináis?

**Comment by David-Estevez** [comment]
Movida a donde corresponde (https://github.com/asrob-uc3m/actas/issues/138).

Comentad en esa issue, hasta el día 15 de Abril, materiales que creéis que faltan además de los cables.
