### ISSUE TITLE
Pegatinas de ASROB para portatil

### ISSUE THREAD

**Issue by wensicm** [asrob-uc3m/ASROB-racing#9]
Desde lo más profundo de nuestro ser, los participantes de ASROB-racing rogamos a ASROB que se "partan la pana" y nos compren unas pegatinas para los portatiles con el slogan de ASROB. Si nos prometeis que las comprais, nosotros podemos hacer un slogan de ASROB racing especial para esta subdivisión.
Y por cierto, @madelgj queria proponer algo de un altavoz que se podía lanzar a la cabeza de la gente y no se rompía (no me quedó claro que era lo que no se rompía si la cabeza o, el altavoz) asi que Mar, manifiestate en esta Issue ._.'

**Comment by David-Estevez** [comment]
Hola!

Como este es un tema del que se puede beneficiar toda la Asociación, casi mejor pon la issue en el repo de actas, que es el que usamos para temas globales: https://github.com/asrob-uc3m/actas/issues

Sobre financiarlas, lo mejor será ver cuánta gente está interesada y hacer bote entre todos para comprarlas.

**Comment by David-Estevez** [comment]
Mucho "David hazme pegatinas" pero luego no me hacéis ni caso...

Os he movido la issue a https://github.com/asrob-uc3m/actas/issues/136 para captar más gente interesada.
